/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module circuit(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst;
  wire rst;
  \$_NOT_  _14_ (
    .A(count[0]),
    .Y(_02_)
  );
  \$_NAND_  _15_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_00_)
  );
  \$_XNOR_  _16_ (
    .A(_00_),
    .B(count[2]),
    .Y(_08_)
  );
  \$_ANDNOT_  _17_ (
    .A(count[2]),
    .B(_00_),
    .Y(_01_)
  );
  \$_XOR_  _18_ (
    .A(_01_),
    .B(count[3]),
    .Y(_09_)
  );
  \$_XOR_  _19_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_07_)
  );
  \$_DFF_P_  \count_reg[0]  /* _20_ */ (
    .C(clk),
    .D(_10_),
    .Q(count[0])
  );
  \$_DFF_P_  \count_reg[1]  /* _21_ */ (
    .C(clk),
    .D(_11_),
    .Q(count[1])
  );
  \$_DFF_P_  \count_reg[2]  /* _22_ */ (
    .C(clk),
    .D(_12_),
    .Q(count[2])
  );
  \$_DFF_P_  \count_reg[3]  /* _23_ */ (
    .C(clk),
    .D(_13_),
    .Q(count[3])
  );
  \$_MUX_  _24_ (
    .A(_02_),
    .B(1'h0),
    .S(rst),
    .Y(_10_)
  );
  \$_MUX_  _25_ (
    .A(_07_),
    .B(1'h0),
    .S(rst),
    .Y(_11_)
  );
  \$_MUX_  _26_ (
    .A(_08_),
    .B(1'h0),
    .S(rst),
    .Y(_12_)
  );
  \$_MUX_  _27_ (
    .A(_09_),
    .B(1'h0),
    .S(rst),
    .Y(_13_)
  );
  assign { _05_, _04_, _03_ } = count[3:1];
  assign _06_ = _02_;
endmodule
