/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "circuit.sv:1.1-14.10" *)
module circuit(clk, rst, count);
  wire _00_;
  wire _01_;
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _02_;
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _03_;
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _04_;
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _05_;
  (* src = "circuit.sv:1.68-1.73" *)
  wire _06_;
  (* src = "circuit.sv:1.68-1.73" *)
  wire _07_;
  (* src = "circuit.sv:1.68-1.73" *)
  wire _08_;
  (* src = "circuit.sv:1.68-1.73" *)
  wire _09_;
  wire _10_;
  wire _11_;
  (* force_downto = 32'h00000001 *)
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _12_;
  (* force_downto = 32'h00000001 *)
  (* src = "circuit.sv:8.16-8.25|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _13_;
  (* src = "circuit.sv:1.28-1.31" *)
  input clk;
  wire clk;
  (* src = "circuit.sv:1.68-1.73" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "circuit.sv:1.45-1.48" *)
  input rst;
  wire rst;
  \$_NOT_  _14_ (
    .A(_06_),
    .Y(_02_)
  );
  \$_AND_  _15_ (
    .A(_06_),
    .B(_07_),
    .Y(_10_)
  );
  \$_XOR_  _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_03_)
  );
  \$_NAND_  _17_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  \$_XOR_  _18_ (
    .A(_08_),
    .B(_10_),
    .Y(_04_)
  );
  \$_XNOR_  _19_ (
    .A(_09_),
    .B(_11_),
    .Y(_05_)
  );
  (* \always_ff  = 32'h00000001 *)
  (* src = "circuit.sv:3.3-11.6" *)
  \$_SDFF_PP0_  \count_reg[0]  /* _20_ */ (
    .C(clk),
    .D(_12_[0]),
    .Q(count[0]),
    .R(rst)
  );
  (* \always_ff  = 32'h00000001 *)
  (* src = "circuit.sv:3.3-11.6" *)
  \$_SDFF_PP0_  \count_reg[1]  /* _21_ */ (
    .C(clk),
    .D(_13_[1]),
    .Q(count[1]),
    .R(rst)
  );
  (* \always_ff  = 32'h00000001 *)
  (* src = "circuit.sv:3.3-11.6" *)
  \$_SDFF_PP0_  \count_reg[2]  /* _22_ */ (
    .C(clk),
    .D(_13_[2]),
    .Q(count[2]),
    .R(rst)
  );
  (* \always_ff  = 32'h00000001 *)
  (* src = "circuit.sv:3.3-11.6" *)
  \$_SDFF_PP0_  \count_reg[3]  /* _23_ */ (
    .C(clk),
    .D(_13_[3]),
    .Q(count[3]),
    .R(rst)
  );
  assign _12_[3:1] = count[3:1];
  assign _13_[0] = _12_[0];
  assign _06_ = count[0];
  assign _12_[0] = _02_;
  assign _07_ = count[1];
  assign _13_[1] = _03_;
  assign _08_ = count[2];
  assign _13_[2] = _04_;
  assign _09_ = count[3];
  assign _13_[3] = _05_;
endmodule
